import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Career Advisor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={`${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Grid Background */}
            <div className="grid-background" />

            {/* Fixed Header */}
            <Header />

            {/* Main content */}
            <main className="relative min-h-screen pt-20 overflow-y-auto">
              {children}
            </main>

            {/* Footer */}
            <footer className="bg-muted/50 py-12 relative z-10">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made By Pratham Grover</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
